---
title: "Parsons_Paper_Register #7"
author: "Anna Zhou & Sarah Edelson"
format: pdf
editor: visual
---

```{r}
#| label: setup
#| include: false
library(mosaic)
library(tidyverse)
options(digits = 4)
```

## How many days in a pay period?

-   The Parsons Paper Company register comprises monthly pay periods from January 1861-April 1869

-   Pay periods appear to be a month long with employees typically getting paid on the 1st of the next (?) month

-   Based off the spreadsheet from p. 253, most employees work between 20-30 days each pay period, the average is around 27 so most employees work at least 6 days/week

    -   In Chapter IV of Green's book, she writes that male Holyoke paper makers worked 58-72 hours a week

        -   11.25 hours five days a week + 8.75 hours on Saturday was typical for Holyoke textile mills

    -   Women worked slightly shorter hours

-   Pgs. 261-263 appear to comprise an entire pay period for the month of April in 1868 (most pay periods span \~3 pages in the register)

-   Pgs. [223](https://drive.google.com/file/d/1zowekbvRKdivfTpDqQ92lGSLDRSJSi8I/view?usp=sharing)-225 and Pgs. [261](https://drive.google.com/file/d/1C6xBX3jRQw0QxcSf6NeiUpl8LxLUDHlk/view?usp=sharing)-263 above are exactly one year apart in the register (April 1st 1867 + April 1st 1868)

## How many employees during this era?

-   Counted 92 employees in April 1861, 141 employees in April 1863, 128 employees in April 1864, 131 employees in April 1867, 153 employees in April 1868, 153 employees in April 1869

    -   Average across the measured 6 years = 133 employees between 1861-1869

        -   Subset Pages: 8-10 (1861) 79-81 (1863), 115-117 (1864 - this month also has pay records from the 30th not included in the employee count above) 223-225 (1867), 261-263 (1868), 314-316 (1869)

    -   Number of employees generally increased over time

        -   Green mentions that these mills had abnormally high employee retention rates

-   Some pages have a separate section of employees at the bottom under "Repairs" \-- I included these names in the counts above

    -   Presumably employees whose main role was to repair the machines instead of making paper
    -   There were 5 people under "Repairs" for April 1st, 1867 and 8 under April 1st, 1868

**Quotes from Hickey thesis that may be of relevance to employment from 1861-1869**

-   "In 1861, after a period of severe readjustment just prior to the Civil War, twenty-one of the thirty-six manufactures of fine papers met at Pittsfield...to organize a protrective association. They desired to raise prices which had fallen drastically as the result of a decrease in demand. They agreed to reduce output by about one-third for about three months. This was the first trade association established in the paper industry of the United States....The Parsons Paper Company and the Carew Manufacturing Company were charter members of this organization\" (108)

-   \"Since the discovery of how to utilize wood for the manufacture of paper in 1867, this raw material has been in increasing demand" (84)

-   "several of the local mills were quite large, employing 200 or more workers" and that there were "about 3700 workers employed in the local paper industry at the turn of the century" (4)
